# Generated by Django 5.1.3 on 2024-12-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Taxi',
            new_name='Driver',
        ),
    ]
