# Generated by Django 5.1.3 on 2024-12-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('cuisine', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Meals',
        ),
    ]
